# python3.9 main_pyjom.py -d "/media/root/Toshiba XG3/works/prometheous"
# python3.9 main_pyjom.py -d "/media/root/Toshiba XG3/works/git_atomic_commit"
# python3.9 main_pyjom.py -d "/media/root/Toshiba XG3/works/jubilant-adventure2"
python3.9 main_pyjom.py -d "/media/root/Toshiba XG3/works/agi_computer_control"
# python3.9 main_pyjom.py -d "/media/root/Toshiba XG3/works/pyjom"
# python3.9 main_pyjom.py -d "/media/root/Prima"